#!/usr/bin/env python3

"""gem5 SE configuration approximating DVR paper Table 1."""

import argparse

import m5
from m5.objects import *
from m5.util.convert import toMemorySize


class DVRIntAdd(FUDesc):
    opList = [OpDesc(opClass="IntAlu", opLat=1)]
    count = 4


class DVRIntMult(FUDesc):
    opList = [OpDesc(opClass="IntMult", opLat=3)]
    count = 1


class DVRIntDiv(FUDesc):
    opList = [OpDesc(opClass="IntDiv", opLat=18, pipelined=False)]
    count = 1


class DVRFPAdd(FUDesc):
    opList = [
        OpDesc(opClass="FloatAdd", opLat=3),
        OpDesc(opClass="FloatCmp", opLat=3),
        OpDesc(opClass="FloatCvt", opLat=3),
    ]
    count = 1


class DVRFPMult(FUDesc):
    opList = [
        OpDesc(opClass="FloatMult", opLat=5),
        OpDesc(opClass="FloatMultAcc", opLat=5),
        OpDesc(opClass="FloatMisc", opLat=5),
    ]
    count = 1


class DVRFPDiv(FUDesc):
    opList = [
        OpDesc(opClass="FloatDiv", opLat=6, pipelined=False),
        OpDesc(opClass="FloatSqrt", opLat=6, pipelined=False),
    ]
    count = 1


class DVRVecALU(FUDesc):
    opList = [
        OpDesc(opClass="SimdAlu"), OpDesc(opClass="SimdCmp"),
        OpDesc(opClass="SimdCvt"), OpDesc(opClass="SimdFloatAlu"),
        OpDesc(opClass="SimdFloatCmp"), OpDesc(opClass="SimdFloatCvt"),
        OpDesc(opClass="SimdReduceAlu"), OpDesc(opClass="SimdReduceCmp"),
        OpDesc(opClass="SimdFloatReduceCmp"),
    ]
    count = 3


class DVRVecShift(FUDesc):
    opList = [OpDesc(opClass="SimdShift"), OpDesc(opClass="SimdShiftAcc")]
    count = 2


class DVRVecAdd(FUDesc):
    opList = [
        OpDesc(opClass="SimdAdd"), OpDesc(opClass="SimdAddAcc"),
        OpDesc(opClass="SimdFloatAdd"), OpDesc(opClass="SimdReduceAdd"),
        OpDesc(opClass="SimdFloatReduceAdd"),
    ]
    count = 2


class DVRVecMult(FUDesc):
    opList = [
        OpDesc(opClass="SimdMult"), OpDesc(opClass="SimdMultAcc"),
        OpDesc(opClass="SimdFloatMult"),
        OpDesc(opClass="SimdFloatMultAcc"),
    ]
    count = 2


class DVRVecShuffle(FUDesc):
    opList = [
        OpDesc(opClass="SimdMisc"), OpDesc(opClass="SimdFloatMisc"),
        OpDesc(opClass="SimdDiv"), OpDesc(opClass="SimdSqrt"),
        OpDesc(opClass="SimdFloatDiv"), OpDesc(opClass="SimdFloatSqrt"),
    ]
    count = 2


class DVRFUPool(FUPool):
    FUList = [
        DVRIntAdd(), DVRIntMult(), DVRIntDiv(), DVRFPAdd(), DVRFPMult(),
        DVRFPDiv(), DVRVecALU(), DVRVecShift(), DVRVecAdd(), DVRVecMult(),
        DVRVecShuffle(), PredALU(), RdWrPort(count=4), IprPort(),
    ]


class Table1L1I(Cache):
    size = "32KiB"
    assoc = 4
    tag_latency = 2
    data_latency = 2
    response_latency = 0
    mshrs = 8
    tgts_per_mshr = 20
    is_read_only = True
    writeback_clean = True


class Table1L1D(Cache):
    size = "32KiB"
    assoc = 8
    tag_latency = 4
    data_latency = 4
    response_latency = 0
    mshrs = 24
    tgts_per_mshr = 20
    prefetcher = StridePrefetcher(table_entries="16", table_assoc=4, degree=4)


class Table1L2(Cache):
    size = "256KiB"
    assoc = 8
    tag_latency = 8
    data_latency = 8
    response_latency = 0
    mshrs = 32
    tgts_per_mshr = 12


class Table1L3(Cache):
    size = "8MiB"
    assoc = 16
    tag_latency = 30
    data_latency = 30
    response_latency = 0
    mshrs = 64
    tgts_per_mshr = 12


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cmd", required=True)
    parser.add_argument("--options", default="")
    parser.add_argument("--maxinsts", type=int, default=0)
    parser.add_argument(
        "--restore-checkpoint", default="",
        help="Restore this SE checkpoint before starting the measured run",
    )
    parser.add_argument(
        "--take-checkpoint", default="",
        help=("Write a checkpoint at the --maxinsts exit and stop; use a "
              "DVR-disabled warmup run to create a mode-neutral ROI"),
    )
    parser.add_argument(
        "--l1d-size", default="32KiB",
        help="L1 data-cache capacity; all other Table-1 parameters remain fixed",
    )
    parser.add_argument("--dvr", action="store_true")
    parser.add_argument("--pre", action="store_true",
                        help="Enable the original Precise Runahead Execution")
    parser.add_argument("--pre-branch", action="store_true",
                        help="Allow branches in PRE")
    parser.add_argument("--pre-early-recycle", action="store_true",
                        help="Enable PRE early register recycle")
    parser.add_argument("--oracle", action="store_true",
                        help="Replay future committed load addresses from a trace")
    parser.add_argument("--oracle-trace", default="",
                        help="CSV workload trace generated by a baseline run")
    parser.add_argument("--oracle-lookahead", type=int, default=32,
                        help="Number of future load addresses exposed to Oracle")
    parser.add_argument(
        "--dvr-mode",
        choices=("vr", "offload", "discovery", "full", "nested"),
        default="nested",
    )
    parser.add_argument("--dvr-helper-max-uops", type=int, default=200)
    parser.add_argument(
        "--dvr-vector-chunks",
        action="store_true",
        help="Model DVR compute as 512-bit vector chunks",
    )
    parser.add_argument(
        "--dvr-unlimited-vector-fu",
        action="store_true",
        help="Run vector chunks without shared vector FU constraints",
    )
    parser.add_argument(
        "--dvr-vector-element-bits",
        type=int,
        choices=(8, 16, 32, 64),
        default=64,
        help="Element width used to form 512-bit DVR vector chunks",
    )
    parser.add_argument(
        "--dvr-max-lanes",
        type=int,
        default=0,
        help="Override the maximum DVR source lanes for bounded-window experiments",
    )
    parser.add_argument("--dvr-no-dependent-prefetch", action="store_true")
    parser.add_argument(
        "--dvr-no-bounded-fallback", action="store_true",
        help="Disable speculative launches without a proven loop bound")
    parser.add_argument(
        "--dvr-private-physical-bank", action="store_true",
        help="Use helper-local register storage for an explicit ablation")
    parser.add_argument(
        "--dvr-shared-physical-bank", action="store_true",
        help="Deprecated compatibility flag; shared physical banks are default")
    parser.add_argument(
        "--num-phys-vec-regs", type=int, default=128,
        help=("Physical vector-register count; 128 is the paper/Table-1 "
              "default and larger values are sensitivity-only"),
    )
    parser.add_argument(
        "--num-phys-int-regs", type=int, default=256,
        help=("Physical integer-register count; 256 is the paper/Table-1 "
              "default and larger values are sensitivity-only"),
    )
    parser.add_argument("--discovery-max-insts", type=int, default=512)
    parser.add_argument("--dvr-ndm-threshold", type=int, default=64)
    parser.add_argument("--dvr-ndm-max-insts", type=int, default=512)
    parser.add_argument(
        "--dvr-quality-probe",
        action="store_true",
        help="Attach the strict DVR quality listener to the L1D only",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    system = System()
    system.clk_domain = SrcClockDomain(
        clock="1GHz", voltage_domain=VoltageDomain(voltage="1.0V")
    )
    system.mem_mode = "timing"
    system.mem_ranges = [AddrRange("512MiB")]
    system.cache_line_size = 64

    system.cpu = DerivO3CPU(
        clk_domain=SrcClockDomain(
            clock="4GHz", voltage_domain=system.clk_domain.voltage_domain
        ),
        fetchWidth=5, decodeWidth=5, renameWidth=5, dispatchWidth=5,
        issueWidth=5, wbWidth=5, commitWidth=5, squashWidth=5,
        # Long graph workloads can return enough independent misses in one
        # cycle to queue writebacks beyond gem5's default five future slots.
        # This is transport storage only; wbWidth still limits retirement.
        forwardComSize=64,
        numROBEntries=350, numIQEntries=128, LQEntries=128, SQEntries=72,
        numPhysIntRegs=args.num_phys_int_regs, numPhysFloatRegs=256,
        numPhysVecRegs=args.num_phys_vec_regs,
        branchPred=TAGE_SC_L_8KB(), fuPool=DVRFUPool(),
        enableDVR=args.dvr, dvrMode=args.dvr_mode,
        enablePRE=args.pre,
        enablePREBranch=args.pre_branch,
        enablePREEarlyRecycle=args.pre_early_recycle,
        oraclePrefetch=args.oracle,
        oracleTraceFile=args.oracle_trace,
        oracleLookahead=args.oracle_lookahead,
        # Figure 8's Offload stage is still vector runahead in a detached
        # subthread.  Keep the same 128 scalar-equivalent lane capacity as
        # VR; explicit --dvr-max-lanes remains available for scalar studies.
        dvrMaxLanes=args.dvr_max_lanes if args.dvr_max_lanes > 0 else 128,
        dvrDiscoveryMaxInsts=args.discovery_max_insts,
        dvrHelperMaxUops=args.dvr_helper_max_uops,
        dvrVectorChunkModel=args.dvr_vector_chunks,
        dvrVectorUnlimitedFU=args.dvr_unlimited_vector_fu,
        dvrVectorElementBits=args.dvr_vector_element_bits,
        dvrEnableDependentPrefetch=not args.dvr_no_dependent_prefetch,
        dvrAllowBoundedFallback=not args.dvr_no_bounded_fallback,
        dvrSharedPhysicalBank=not args.dvr_private_physical_bank,
        dvrNDMThreshold=args.dvr_ndm_threshold,
        dvrNDMMaxInsts=args.dvr_ndm_max_insts,
    )
    if args.maxinsts:
        system.cpu.max_insts_any_thread = args.maxinsts

    l1i = Table1L1I()
    l1d = Table1L1D()
    l1d.size = args.l1d_size
    system.cpu.addPrivateSplitL1Caches(l1i, l1d)

    if args.dvr_quality_probe:
        # Derive the shadow geometry from the measured cache so coverage is
        # not computed against a differently-sized counterfactual cache.
        l1d_bytes = toMemorySize(str(l1d.size))
        l1d_sets = l1d_bytes // (int(l1d.assoc) * int(system.cache_line_size))
        # manager is bound to the L1D alone: also listening on L2/L3 would
        # double-count every lookup and fill.
        system.cpu.dvr_quality_probe = DVRQualityProbe(
            manager=l1d,
            sets=l1d_sets,
            assoc=int(l1d.assoc),
            line_bytes=int(system.cache_line_size),
        )

    system.l2bus = L2XBar(frontend_latency=0, forward_latency=0,
                          response_latency=0)
    system.l2 = Table1L2()
    system.l3bus = L2XBar(frontend_latency=0, forward_latency=0,
                          response_latency=0)
    system.l3 = Table1L3()
    system.membus = SystemXBar(frontend_latency=0, forward_latency=0,
                               response_latency=0)

    system.cpu.connectAllPorts(system.l2bus.cpu_side_ports,
                               system.membus.cpu_side_ports,
                               system.membus.mem_side_ports)
    # DVR helper instruction fetches use a separate timing port so they do not
    # mutate the main O3 Fetch stage's outstanding-request state.
    system.cpu.dvr_icache_port = system.l2bus.cpu_side_ports
    system.l2.cpu_side = system.l2bus.mem_side_ports
    system.l2.mem_side = system.l3bus.cpu_side_ports
    system.l3.cpu_side = system.l3bus.mem_side_ports
    system.l3.mem_side = system.membus.cpu_side_ports

    system.memory = SimpleMemory(
        range=system.mem_ranges[0], latency="50ns", bandwidth="51.2GB/s"
    )
    system.memory.port = system.membus.mem_side_ports
    system.system_port = system.membus.cpu_side_ports

    process = Process(pid=100)
    process.executable = args.cmd
    process.cmd = [args.cmd] + (args.options.split() if args.options else [])
    system.workload = SEWorkload.init_compatible(args.cmd)
    system.cpu.workload = process
    system.cpu.createThreads()
    system.cpu.createInterruptController()

    root = Root(full_system=False, system=system)
    if args.take_checkpoint and not args.maxinsts:
        raise RuntimeError("--take-checkpoint requires --maxinsts")

    m5.instantiate(args.restore_checkpoint or None)
    if args.restore_checkpoint:
        # Checkpoints preserve warmed caches, predictor and architectural
        # state.  Only the post-restore interval belongs to the ROI.
        m5.stats.reset()
    event = m5.simulate()
    print("Exiting @ tick {} because {}".format(m5.curTick(), event.getCause()))
    if args.take_checkpoint:
        m5.checkpoint(args.take_checkpoint)
        print("Checkpoint written to {}".format(args.take_checkpoint))


if __name__ == "__m5_main__":
    main()
